# --- Minimal Gruvbox Status Bar ---

# Show the bar and center the window list
set -g status on
set -g status-justify centre

set -g status-left '#[fg=green,bold] #S #[default]                                                                '
set -g status-left-length 30

# Remove right section
set -g status-right '#(~/.config/tmux/conf/fortune.sh)'
set -g status-right-length 30

# Status bar background / foreground
set -g status-bg default
set -g status-fg white

# Window list separator
set -g window-status-separator "·"

# Inactive windows: grey (brightblack)
set -g window-status-format "#[fg=brightblack]#I #W#[default]"

# Active window: orange (orange in Gruvbox = colour166)
set -g window-status-current-format "#[fg=colour166]#I #W#[default]"

# No highlight / no bold / no background
set -g window-status-current-style none
set -g window-status-style none

set -g status-bg black
set -g status-fg white

