[opener]
zathura = [
    { run = 'zathura "$@"', desc = "Open with Zathura", for = "unix" }
]

[open]
rules = [
	# Custom pdf rule
    { mime = "application/pdf", use = "zathura" },
    { name = "*.pdf", use = "zathura" },
    
    # Default rules
    { mime = "inode/directory", use = "cd" },
    { mime = "text/*", use = "edit" },
    { mime = "image/*", use = "open" },
    { mime = "video/*", use = "open" },
    { mime = "audio/*", use = "open" },
    { use = "open" }
]
