run '$HOMEBREW_PREFIX/opt/tpm/share/tpm/tpm'

set-hook -g after-new-window 'run-shell "tmux run-shell -t \"#{window_id}\" \"fastfetch\""'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'egel/tmux-gruvbox'
set -g @plugin 'mrjones2014/smart-splits.nvim'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# For scrolling
set -g mouse on

# For copying
set -g set-clipboard on
set -g allow-passthrough on
set -g focus-events on

# Theme
set -g @tmux-gruvbox 'dark'
set -g pane-active-border-style "bg=default,fg=colour166"
set -g pane-border-style "bg=default,fg=colour245"
set -g pane-border-lines "heavy"

# Keybindings

# Important Defaults
# bind-key , command-prompt -I '#W' 'rename-window -- "%%"'
# bind-key $ command-prompt -I '#S' 'rename-session -- "%%"'
# bind s choose-tree -Zs
# bind c new-window
# bind <num> select window

bind k kill-pane
bind S command-prompt -p "New Session Name:" "new-session -A -s '%%'"
bind K confirm-before -p "kill-session #S? (y/n)" "switch-client -l \; kill-session -t #S"

set -g @resurrect-save 'W' # Write
set -g @resurrect-restore 'R'

# Toggle fullscreen pane
unbind z
bind Enter resize-pane -Z

unbind C-b
set-option -g prefix M-Space
bind-key M-Space send-prefix

set -g @smart-splits_no_wrap '' # to disable wrapping. (any value disables wrapping)
set -g @smart-splits_move_left_key  'C-h'
set -g @smart-splits_move_down_key  'C-j'
set -g @smart-splits_move_up_key    'C-k'
set -g @smart-splits_move_right_key 'C-l'
set -g @smart-splits_resize_left_key  'C-Left'
set -g @smart-splits_resize_down_key  'C-Down'
set -g @smart-splits_resize_up_key    'C-Up'
set -g @smart-splits_resize_right_key 'C-Right'
set -g @smart-splits_resize_step_size '3' 

bind r source-file ~/.config/tmux/tmux.conf

bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# Browse tmux pane in nvim
bind [ run-shell 'kitty @ kitten /Users/sumeet/.local/share/nvim/lazy/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py --env "TMUX=$TMUX" --env "TMUX_PANE=#{pane_id}"'


run '~/.tmux/plugins/tpm/tpm'
