run '$HOMEBREW_PREFIX/opt/tpm/share/tpm/tpm'

TMUX_CONF_DIR="$HOME/.config/tmux/conf"
source-file "$TMUX_CONF_DIR/hooks.conf"
source-file "$TMUX_CONF_DIR/keybindings.conf"
source-file "$TMUX_CONF_DIR/statusbar.conf"

set-hook -g after-new-window 'run-shell "tmux run-shell -t \"#{window_id}\" \"fastfetch\""'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'egel/tmux-gruvbox'
set -g @plugin 'mrjones2014/smart-splits.nvim'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# For scrolling
set -g mouse on

# For copying
set -g set-clipboard on
set -g allow-passthrough on
set -g focus-events on
# Theme
set -g @tmux-gruvbox 'dark'
set -g pane-active-border-style "bg=default,fg=colour166"
set -g pane-border-style "bg=default,fg=colour245"
set -g pane-border-lines "heavy"

set -gq allow-passthrough on

run '~/.tmux/plugins/tpm/tpm'
